### ISSUE TITLE
About　shape???

### ISSUE THREAD

**Issue by Easyfeng222** [LossNAN/I3D-Tensorflow#20]
Traceback (most recent call last):
  File "train_ucf_rgb.py", line 180, in <module>
    tf.app.run()
  File "/home/feng/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/feng/anaconda3/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/feng/anaconda3/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "train_ucf_rgb.py", line 176, in main
    run_training()
  File "train_ucf_rgb.py", line 136, in run_training
    is_training: True
  File "/home/feng/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/feng/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1149, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (8, 16, 224, 224, 3) for Tensor 'Placeholder:0', which has shape '(8, 64, 224, 224, 3)'

我实在找不到错误了，求大神帮着看一下，感谢

**Comment by rayush7** [comment]
Hi @Easyfeng222 

I am facing the same issue as you. Did you find the solution?

**Comment by chongchiwanghou** [comment]
I have the same problem, can someone fix it?

**Comment by rayush7** [comment]
Try setting
sample_rate = 1 

in this line
https://github.com/LossNAN/I3D-Tensorflow/blob/master/input_data.py#L168

**Comment by GayatriPurandharT** [comment]
@rayush7  that doesn't help me. The error still persists.
It's strange that I get `TypeError: 'range' object does not support item assignment` at the same line numbers as in @Easyfeng222 's question.
```
Traceback (most recent call last):
  File "train_ucf_rgb.py", line 181, in <module>
    tf.app.run()
  File "/home/fb180/anaconda3/envs/i3denv/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/fb180/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/fb180/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train_ucf_rgb.py", line 177, in main
    run_training()
  File "train_ucf_rgb.py", line 132, in run_training
    shuffle=True
  File "../../input_data.py", line 184, in read_clip_and_label
    random.shuffle(video_indices)
  File "/home/fb180/anaconda3/envs/i3denv/lib/python3.6/random.py", line 277, in shuffle
    x[i], x[j] = x[j], x[i]
TypeError: 'range' object does not support item assignment
```
This is my error message.
@LossNAN help in this problem would be greatly appreciated.
Thanks!

**Comment by THUHJ** [comment]
@GayatriPurandharT 
try "video_indices = range(len(lines))" to "video_indices = list(range(len(lines)))"
in "input_data.py"
