### ISSUE TITLE
Dear author  According to the README I have encountered some problems.   python train_ucf_flow.py

### ISSUE THREAD

**Issue by Jiangchitang** [LossNAN/I3D-Tensorflow#9]
File "../../input_data.py", line 194, in read_clip_and_label
    tmp_label = line[1]
IndexError: list index out of range

Looking forward to your answer

**Comment by Jiangchitang** [comment]
python '/home/jhy/3DCNN/I3D-Tensorflow-master/experiments/ucf-101/train_ucf_flow.py' 
(6, 1, 1, 1, 1024)
Tensor("Placeholder_2:0", shape=(6,), dtype=int64)
Tensor("Flow/inception_i3d/Mean:0", shape=(6, 2), dtype=float32)
(6, 2)
2019-01-29 23:27:28.902327: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/home/jhy/3DCNN/I3D-Tensorflow-master/experiments/ucf-101/train_ucf_flow.py", line 183, in <module>
    tf.app.run()
  File "/home/jhy/yes/envs/I3D/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/jhy/3DCNN/I3D-Tensorflow-master/experiments/ucf-101/train_ucf_flow.py", line 179, in main
    run_training()
  File "/home/jhy/3DCNN/I3D-Tensorflow-master/experiments/ucf-101/train_ucf_flow.py", line 133, in run_training
    shuffle=True
  File "../../input_data.py", line 194, in read_clip_and_label
    tmp_label = line[1]
IndexError: list index out of range
